---
- name: "Add Node.js from Nodesource"
  become: true 
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    sudo apt-get install -y nodejs
    sudo npm install -g n #installing n version manager
    sudo n 13.8.0

- name: "Install PM2"
  npm:
    name: pm2
    global: yes